trunk/l10n/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^setlang/$', 'django.views.i18n.set_language', {}, 'satchmo_set_language'),
)

trunk/marvin/store/addons/newsletter/urls.py
"""
URLConf for Satchmo Newsletter app

This will get automatically added by satchmo_store, under the url given in your livesettings "NEWSLETTER","NEWSLETTER_SLUG"
"""

from django.conf.urls.defaults import *
from livesettings import config_value
import logging
log = logging.getLogger('newsletter.urls')

urlpatterns = patterns('satchmo_ext.newsletter.views',
    (r'^subscribe/$', 'add_subscription', {}, 'newsletter_subscribe'),
    (r'^subscribe/ajah/$', 'add_subscription', 
        {'result_template' : 'newsletter/ajah.html'}, 'newsletter_subscribe_ajah'),
    (r'^unsubscribe/$', 'remove_subscription', 
        {}, 'newsletter_unsubscribe'),
    (r'^unsubscribe/ajah/$', 'remove_subscription', 
        {'result_template' : 'newsletter/ajah.html'}, 'newsletter_unsubscribe_ajah'),
    (r'^update/$', 'update_subscription', {}, 'newsletter_update'),
)

newsbase = r'^' + config_value('NEWSLETTER','NEWSLETTER_SLUG') + '/'    
newspatterns = patterns('',
    (newsbase, include('satchmo_ext.newsletter.urls'))
)

def add_newsletter_urls(sender, patterns=(), **kwargs):
    log.debug("Adding newsletter urls at %s", newsbase)
    patterns += newspatterns

trunk/marvin/store/addons/newsletter/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from satchmo_store.contact.models import Contact
import datetime
import logging

log = logging.getLogger('newsletter.models')

_NOTSET = object()

class NullContact(object):
    """Simple object emulating a Contact, so that we can add users who aren't Satchmo Contacts.

    Note, this is *not* a Django object, and is not saved to the DB, only to the subscription lists.
    """

    def __init__(self, full_name, email):
        if not full_name:
            full_name = email.split('@')[0]

        self.full_name = full_name
        self.email = email

def get_contact_or_fake(full_name, email):
    """Get a `Contact` by email or if it doesn't exist, then a `NullContact`"""
    try:
        contact = Contact.objects.get(email=email)

    except Contact.DoesNotExist:
        contact = NullContact(full_name, email)

    return contact

class Subscription(models.Model):
    """A newsletter subscription."""

    subscribed = models.BooleanField(_('Subscribed'), default=True)
    email = models.EmailField(_('Email'), max_length=75)
    create_date = models.DateField(_("Creation Date"))
    update_date = models.DateField(_("Update Date"))

    def email_is_subscribed(cls, email):
        try:
            sub = cls.objects.get(email=email)
            return sub.subscribed
        except cls.DoesNotExist:
            return False

    email_is_subscribed = classmethod(email_is_subscribed)

    def __unicode__(self):
        if self.subscribed:
            flag="Y"
        else:
            flag="N"
        return u"[%s] %s" % (flag, self.email)

    def __repr__(self):
        return "<Subscription: %s>" % str(self)

    def attribute_value(self, name, value=_NOTSET):
        """Get a value from an attribute."""
        try:
            att = self.attributes.get(name=name)
            value = att.value
        except SubscriptionAttribute.DoesNotExist:
            if value != _NOTSET:
                raise

        return value

    def save(self, **kwargs):
        if not self.pk:
            self.create_date = datetime.date.today()

        self.update_date = datetime.date.today()

        super(Subscription, self).save(**kwargs)
                
    def update_attribute(self, name, value):
        """Update or create a `SubscriptionAttribute` object with the passed `name` and `value`."""
        value = str(value)
        try:
            att = self.attributes.get(name=name)
            att.value = value
        except SubscriptionAttribute.DoesNotExist:
            att = SubscriptionAttribute(subscription=self, name=name, value=value)
        
        att.save()
        return att

    def update_attributes(self, attributes):
        """Update `SubscriptionAttribute` objects from a dictionary of name val mappings."""
        return [self.update_attribute(name, value) for name, value in attributes.items()]

        
class SubscriptionAttribute(models.Model):
    """
    Allows arbitrary name/value pairs (as strings) to be attached to a subscription.
    """
    subscription = models.ForeignKey(Subscription, related_name="attributes")
    name = models.SlugField(_("Attribute Name"), max_length=100, )
    value = models.CharField(_("Value"), max_length=255)

    class Meta:
        verbose_name = _("Subscription Attribute")
        verbose_name_plural = _("Subscription Attributes")

import config
import listeners
listeners.start_listening()

trunk/marvin/store/addons/newsletter/forms.py
"""Base forms for use in newsletter subscribing"""

from django import forms
from django.utils.translation import ugettext_lazy as _
from satchmo_ext.newsletter import update_subscription
from satchmo_ext.newsletter.models import get_contact_or_fake

_NOTSET = object()

class OptionalBoolean(forms.BooleanField):
    def __init__(self, *args, **kwargs):
        forms.BooleanField.__init__(self, *args, **kwargs)
        self.required = False

class NewsletterForm(forms.Form):
    full_name = forms.CharField(label=_('Full Name'), max_length=100, required=False)
    email = forms.EmailField(label=_('Email address'), max_length=75, required=True)
    subscribed = OptionalBoolean(label=_('Subscribe'), required=False, initial=True)

    def get_contact(self):
        data = self.cleaned_data
        email = data['email']
        full_name = data['full_name']
        
        return get_contact_or_fake(full_name, email)
    
    def save(self, state=_NOTSET, attributes={}):
        contact = self.get_contact()
        if state == _NOTSET:
            state = self.cleaned_data['subscribed']
        return update_subscription(contact, state, attributes=attributes)

trunk/marvin/store/addons/newsletter/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _, ugettext
from satchmo_ext.newsletter.forms import NewsletterForm

def add_subscription(request, template="newsletter/subscribe_form.html", 
    result_template="newsletter/update_results.html", form=NewsletterForm):
    """Add a subscription and return the results in the requested template."""

    return _update(request, True, template, result_template, form=form)

def remove_subscription(request, template="newsletter/unsubscribe_form.html",
    result_template="newsletter/update_results.html", form=NewsletterForm):
    """Remove a subscription and return the results in the requested template."""

    return _update(request, False, template, result_template, form=form)

def update_subscription(request, template="newsletter/update_form.html", 
    result_template="newsletter/update_results.html", form=NewsletterForm):
    """Add a subscription and return the results in the requested template."""

    return _update(request, 'FORM', template, result_template, form=form)

def _update(request, state, template, result_template, form=NewsletterForm):
    """Add a subscription and return the results in the requested template."""
    success = False
    result = ""

    if request.method == "POST":
        workform = form(request.POST)
        if workform.is_valid():
            if state == 'FORM':
                # save with subcription status from form
                result = workform.save()
            else:
                # save with subscription status explicitly set
                result = workform.save(state)
            success = True
        else:
            result = ugettext('Error, not valid.')

    else:
        workform = form()

    ctx = RequestContext(request, {
        'result' : result,
        'form' : workform
    })

    if success:
        return render_to_response(result_template, context_instance=ctx)
    else:
        return render_to_response(template, context_instance=ctx)

trunk/marvin/store/addons/newsletter/templates/newsletter/ajah.html
{{ result }}

trunk/marvin/store/addons/newsletter/templates/newsletter/subscribe_form.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block navbar %}
   <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
   <li>{% trans "Newsletter Subscription" %}</li>
{% endblock %}

{% block content %}
<h3>{% trans "Newsletter Subscription" %}</h3>

{% if form.errors %}
<h3>{% blocktrans count form.errors|length as count %}Please correct the following error:{% plural %}Please correct the following errors:{% endblocktrans %}</h3>
{% endif %}

<table>
<form method="post" action="{% url newsletter_subscribe %}">
	<tr><td><label for="id_full_name">{% trans 'Your name' %}:</label></td><td>{{ form.full_name }}</td></tr>
	{% if form.full_name.errors %}<tr><td>&nbsp;</td><td>*** {{ form.full_name.errors|join:", " }}</td></tr>{% endif %}
	<tr><td><label for="id_email">{% trans 'Email address' %}:</label></td><td>{{ form.email }}</td></tr>
	{% if form.email.errors %}<tr><td>&nbsp;</td><td>*** {{ form.email.errors|join:", " }}</td></tr>{% endif %}
	<input type="hidden" value="on" name="subscribed"/>
	<tr><td></td><td><input type="submit" value="{% trans "Subscribe" %}"/></td></tr>
</form>
</table>
{% endblock %}

trunk/marvin/store/addons/newsletter/templates/newsletter/unsubscribe_form.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block navbar %}
   <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
   <li>{% trans "Newsletter Unsubscribe" %}</li>
{% endblock %}

{% block content %}
<h3>{% trans "Newsletter Unsubscribe" %}</h3>

{% if form.errors %}
<h3>{% blocktrans count form.errors|length as count %}Please correct the following error:{% plural %}Please correct the following errors:{% endblocktrans %}</h3>
{% endif %}

<form method="post" action="{% url newsletter_unsubscribe %}">
	<table>
	<tr><td><label for="id_full_name">{% trans 'Your name' %}:</label></td><td>{{ form.full_name }}</td></tr>
	{% if form.full_name.errors %}<tr><td>&nbsp;</td><td>*** {{ form.full_name.errors|join:", " }}</td></tr>{% endif %}
	<tr><td><label for="id_email">{% trans 'Email address' %}:</label></td><td>{{ form.email }}</td></tr>
	{% if form.email.errors %}<tr><td>&nbsp;</td><td>*** {{ form.email.errors|join:", " }}</td></tr>{% endif %}
	<tr><td></td><td><input type="submit" value="{% trans "Remove Me" %}"/></td></tr>
	<input type="hidden" value="off" name="subscribed"/>
	</table>
</form>
<div style="clear:both;"/>
{% endblock %}

trunk/marvin/store/addons/newsletter/templates/newsletter/update_form.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block navbar %}
   <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
   <li>{% trans "Newsletter Subscription" %}</li>
{% endblock %}

{% block content %}
<h3>{% trans "Newsletter Subscription" %}</h3>

{% if form.errors %}
<h3>{% blocktrans count form.errors|length as count %}Please correct the following error:{% plural %}Please correct the following errors:{% endblocktrans %}</h3>
{% endif %}

<form method="post" action="{% url newsletter_update %}">
	<table>
	<tr><td><label for="id_full_name">{% trans 'Your name' %}:</label></td><td>{{ form.full_name }}</td></tr>
	{% if form.full_name.errors %}<tr><td>&nbsp;</td><td>*** {{ form.full_name.errors|join:", " }}</td></tr>{% endif %}
	<tr><td><label for="id_email">{% trans 'Email address' %}:</label></td><td>{{ form.email }}</td></tr>
	{% if form.email.errors %}<tr><td>&nbsp;</td><td>*** {{ form.email.errors|join:", " }}</td></tr>{% endif %}
	<tr><td><label for="id_subscribed">{% trans 'Subscribe' %}:</label></td><td>{{ form.subscribed }}</td></tr>
	{% if form.subscribed.errors %}<tr><td>&nbsp;</td><td>*** {{ form.subscribed.errors|join:", " }}</td></tr>{% endif %}
	<tr><td></td><td><input type="submit" value="{% trans "Subscribe" %}"/></td></tr>

	</table>
</form>

{% endblock %}

trunk/marvin/store/addons/newsletter/templates/newsletter/update_results.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block navbar %}
   <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
   <li>{% trans "Newsletter Subscription" %}</li>
{% endblock %}

{% block content %}
<h3>{% trans "Newsletter Subscription" %}</h3>

<p>{{ result }}</p>

{% endblock %}