trunk/l10n/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^setlang/$', 'django.views.i18n.set_language', {}, 'satchmo_set_language'),
)

trunk/marvin/core/contacts/urls.py
from django.conf.urls.defaults import patterns

urlpatterns = patterns('marvin.core.contacts.views',
    (r'^$', 'view', {}, 'profile_info'),
    (r'^update/$', 'update', {}, 'profile_update'),
    (r'^ajax_state/$', 'ajax_get_state', {}, 'satchmo_contact_ajax_state'),
)

trunk/marvin/core/contacts/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.localflavor.us.models import PhoneNumberField

from l10n.models import Country


class Contact(models.Model):
    """
    Contact is a record of details on any individual that a customer
    may add to his/her account overtime. This could be details on his
    wife, or parents, or anyone. This allows him to store these details
    to mail out things directly to there contacts and other seemingly
    useful things.
    """
    user = models.ForeignKey(User, related_name='contacts')
    relationship = models.CharField(_("Relationship"), max_length=50, blank=True, null=True)
    title = models.CharField(_("Title"), max_length=30, blank=True, null=True)
    first_name = models.CharField(_("First name"), max_length=30, )
    last_name = models.CharField(_("Last name"), max_length=30, )
    dob = models.DateField(_("Date of birth"), blank=True, null=True)
    email = models.EmailField(_("Email"), blank=True, max_length=75)
    notes = models.TextField(_("Notes"), max_length=500, blank=True)
    is_primary = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_full_name(self):
        """Return the person's full name."""
        return u'%s %s' % (self.first_name, self.last_name)

    @property
    def full_name(self):
        return self.get_full_name()

    def __unicode__(self):
        return self.get_full_name()

    class Meta:
        verbose_name = _("Contact")
        verbose_name_plural = _("Contacts")


PHONE_CHOICES = (
    ('Work', _('Work')),
    ('Home', _('Home')),
    ('Fax', _('Fax')),
    ('Mobile', _('Mobile')),
)

SOCIAL_SERVICES = (
    ('Facebook', _('Facebook')),
    ('Twitter', _('Twitter')),
    ('LinkedIn', _('LinkedIn')),
    ('MySpace', _('MySpace')),
    ('Skype', _('Skype')),
)

SOCIAL_SERVICES_BASE = {
    'Facebook': 'http://www.facebook.com/%s',
    'Twitter': 'http://www.twitter.com/%s',
    'LinkedIn': 'http://www.linkedin.com/in/%s',
    'MySpace': 'http://myspace.com/%s',
}

PRIVACY_SETTINGS = (
    ('public', _('Visible to your downline and potential leads')),
    ('private', _('Visible only to you')),
    ('downline', _('Visible only to your downline')),
)


class SocialNetwork(models.Model):
    """
    Social network account
    """
    user = models.ForeignKey(User, related_name='social')
    service = models.CharField(max_length=30, choices=SOCIAL_SERVICES)
    account = models.CharField(max_length=255)
    privacy_settings = models.CharField(max_length=30, choices=PRIVACY_SETTINGS)
    
    created = models.DateTimeField(_('Created Date and Time'), auto_now_add=True)
    updated = models.DateTimeField(_('Updated Date and Time'), auto_now=True)
    
    def __unicode__(self):
        return u'%s - %s' % (self.get_service_display, self.account)

    def url(self):
        if 'http' in self.account:
            return self.account
        else:
            base = SOCIAL_SERVICES_BASE.get(self.service, '')
            return base % ( self.account )

    class Meta:
        verbose_name = _('Social Network Account')
        verbose_name_plural = _('Social Network Accounts')


class PhoneNumber(models.Model):
    """
    Phone number associated with a contact.
    """
    user = models.ForeignKey(User, related_name='phones')
    type = models.CharField(_("Description"), choices=PHONE_CHOICES, max_length=20)
    phone = PhoneNumberField(_("Phone Number")) 
    privacy_setting = models.CharField(max_length=30, choices=PRIVACY_SETTINGS)
    is_primary = models.BooleanField(_("Primary"), default=False)

    @property
    def number(self):
        return self.phone

    def __unicode__(self):
        return u'%s Phone - %s' % (self.type, self.phone)

    def save(self, **kwargs):
        """
        If this number is the default, then make sure that it is the only
        primary phone number. If there is no existing default, then make
        this number the default.
        """
        existing_number = False # self.user.primary_phone
        if existing_number:
            if self.primary:
                existing_number.primary = False
                #existing_number.save() # this would rerun the check and break
                super(PhoneNumber, existing_number).save()
        else:
            self.primary = True
        super(PhoneNumber, self).save(**kwargs)

    class Meta:
        ordering = ['-is_primary']
        verbose_name = _("Phone Number")
        verbose_name_plural = _("Phone Numbers")


class AddressBook(models.Model):
    """
    Address information associated with a contact.
    """
    user = models.ForeignKey(User, related_name='addresses')
    description = models.CharField(_("Description"), max_length=20, blank=True, help_text=_('Description of address - Home, Office, Warehouse, etc.',))
    addressee = models.CharField(_("Addressee"), max_length=80)
    street1 = models.CharField(_("Street"), max_length=80)
    street2 = models.CharField(_("Street"), max_length=80, blank=True, null=True)
    state = models.CharField(_("State"), max_length=50, blank=True)
    city = models.CharField(_("City"), max_length=50)
    postal_code = models.CharField(_("Zip Code"), max_length=30)
    country = models.ForeignKey(Country, verbose_name=_("Country"))

    is_default_shipping = models.BooleanField(default=False)
    is_default_billing = models.BooleanField(default=False)

    def __unicode__(self):
       return u'%s - %s address' % (self.user.get_full_name(), self.description)

    class Meta:
        verbose_name = _("Address Book")
        verbose_name_plural = _("Address Books")

import utils
User.add_to_class('contact', utils.get_primary_contact)
User.add_to_class('phone', utils.get_primary_phone_number)
User.add_to_class('shipping_address', utils.get_shipping_address)
User.add_to_class('billing_address', utils.get_billing_address)

import config

trunk/marvin/core/contacts/forms.py
from django import forms
from django.db.models import Q
from django.forms.extras.widgets import SelectDateWidget
from django.utils.translation import ugettext_lazy as _, ugettext
from l10n.models import Country
from marvin.utils.dbsettings import config_value
from marvin.core.contacts.models import Contact, AddressBook, PhoneNumber, SocialNetwork
from marvin.store.shop.models import Config
from marvin.store.shop.util import clean_field
from marvin.utils.signals_ahoy.signals import form_init, form_initialdata, form_postsave
import datetime
import logging
import signals

log = logging.getLogger('marvin.core.contacts.forms')

selection = ''

def area_choices_for_country(country, translator=_):
    choices = [('',translator("Not Applicable"))]

    if country:
        areas = country.adminarea_set.filter(active=True)
        if areas.count()>0:
            choices = [('',translator("---Please Select---"))]
            choices.extend([(area.abbrev or area.name, area.name) for area in areas])

    return choices

class AddressBookForm(forms.ModelForm):
    class Meta:
        model = AddressBook
        exclude = ('user', 'description', 'is_default_billing', 'is_default_shipping', )

class ProxyContactForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user', None)
        self._contact = kwargs.pop('contact', None)
        super(ProxyContactForm, self).__init__(*args, **kwargs)

class ContactInfoForm(ProxyContactForm):
    email = forms.EmailField(max_length=75, label=_('Email'), required=False)
    title = forms.CharField(max_length=30, label=_('Title'), required=False)
    first_name = forms.CharField(max_length=30, label=_('First Name'), required=False)
    last_name = forms.CharField(max_length=30, label=_('Last Name'), required=False)
    #phone = forms.CharField(max_length=30, label=_('Phone'), required=False)
    addressee = forms.CharField(max_length=61, label=_('Addressee'), required=False)
    street1 = forms.CharField(max_length=30, label=_('Street'), required=False)
    street2 = forms.CharField(max_length=30, required=False)
    city = forms.CharField(max_length=30, label=_('City'), required=False)
    state = forms.CharField(max_length=30, label=_('State'), required=False)
    postal_code = forms.CharField(max_length=10, label=_('ZIP code/Postcode'), required=False)
    copy_address = forms.BooleanField(label=_('Shipping same as billing?'), required=False)
    ship_addressee = forms.CharField(max_length=61, label=_('Addressee'), required=False)
    ship_street1 = forms.CharField(max_length=30, label=_('Street'), required=False)
    ship_street2 = forms.CharField(max_length=30, required=False)
    ship_city = forms.CharField(max_length=30, label=_('City'), required=False)
    ship_state = forms.CharField(max_length=30, label=_('State'), required=False)
    ship_postal_code = forms.CharField(max_length=10, label=_('ZIP code/Postcode'), required=False)
    next = forms.CharField(max_length=200, widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial', {})
        #form_initialdata.send(self.__class__, form=self, initial=initial, contact = kwargs.get('contact', None))
        kwargs['initial'] = initial

        shop = kwargs.pop('shop', None)
        shippable = kwargs.pop('shippable', True)
        super(ContactInfoForm, self).__init__(*args, **kwargs)
        if not shop:
            shop = Config.objects.get_current()
        self._shop = shop
        self._shippable = shippable

        self.required_billing_data = config_value('SHOP', 'REQUIRED_BILLING_DATA')
        self.required_shipping_data = config_value('SHOP', 'REQUIRED_SHIPPING_DATA')
        self._local_only = shop.in_country_only
        self.enforce_state = config_value('SHOP','ENFORCE_STATE')

        self._default_country = shop.sales_country
        billing_country = (self._user and getattr(self._user.billing_address, 'country', None)) or self._default_country
        shipping_country = (self._user and getattr(self._user.shipping_address, 'country', None)) or self._default_country
        self.fields['country'] = forms.ModelChoiceField(shop.countries(), required=False, label=_('Country'), empty_label=None, initial=billing_country.pk) #SMA python2.6 if billing_country else None)
        self.fields['ship_country'] = forms.ModelChoiceField(shop.countries(), required=False, label=_('Country'), empty_label=None, initial=shipping_country.pk) #SMA python2.6 if shipping_country else None)

        if self.enforce_state:
            # if self.is_bound and not self._local_only:
            if self.is_bound and not self._local_only:
                # If the user has already chosen the country and submitted,
                # populate accordingly.
                #
                # We don't really care if country fields are empty;
                # area_choices_for_country() handles those cases properly.
                billing_country_data = clean_field(self, 'country')
                shipping_country_data = clean_field(self, 'ship_country')

                # Has the user selected a country? If so, use it.
                if billing_country_data:
                    billing_country = billing_country_data

                if clean_field(self, "copy_address"):
                    shipping_country = billing_country
                elif shipping_country_data:
                    shipping_country = shipping_country_data

            # Get areas for the initial country selected.
            billing_areas = area_choices_for_country(billing_country)
            shipping_areas = area_choices_for_country(shipping_country)

            billing_state = (self._user and getattr(self._user.billing_address, 'state', None)) or selection
            self.fields['state'] = forms.ChoiceField(choices=billing_areas, initial=billing_state, label=_('State'),
                # if there are not states, then don't make it required. (first
                # choice is always either "--Please Select--", or "Not
                # Applicable")
                required=len(billing_areas)>1)

            shipping_state = (self._user and getattr(self._user.shipping_address, 'state', None)) or selection
            self.fields['ship_state'] = forms.ChoiceField(choices=shipping_areas, initial=shipping_state, required=False, label=_('State'))

        for fname in self.required_billing_data:
            if fname == 'country' and self._local_only:
                continue

            # ignore the user if ENFORCE_STATE is on; if there aren't any
            # states, we might have made the billing state field not required in
            # the enforce_state block earlier, and we don't want the user to
            # make it required again.
            if fname == 'state' and self.enforce_state:
                continue

            self.fields[fname].required = True

        # if copy_address is on, turn of django's validation for required fields
        if not (self.is_bound and clean_field(self, "copy_address")):
            for fname in self.required_shipping_data:
                if fname == 'country' and self._local_only:
                    continue
                self.fields['ship_%s' % fname].required = True

        # slap a star on the required fields
        for f in self.fields:
            fld = self.fields[f]
            if fld.required:
                fld.label = (fld.label or f) + '*'
        log.info('Sending form_init signal: %s', self.__class__)
        form_init.send(self.__class__, form=self)

    def _check_state(self, data, country):
        if country and self.enforce_state and country.adminarea_set.filter(active=True).count() > 0:
            if not data or data == selection:
                raise forms.ValidationError(
                    self._local_only and _('This field is required.') \
                               or _('State is required for your country.'))
            if (country.adminarea_set
                        .filter(active=True)
                        .filter(Q(name__iexact=data)|Q(abbrev__iexact=data))
                        .count() != 1):
                raise forms.ValidationError(_('Invalid state or province.'))
        return data


    def clean_email(self):
        """Prevent account hijacking by disallowing duplicate emails."""
        email = self.cleaned_data.get('email', None)
        if self._user:
            if self._user.email and self._user.email == email:
                return email
            
            users_with_email = Contact.objects.filter(email=email)
            
            if len(users_with_email) == 0:
                return email

            if len(users_with_email) > 1 or users_with_email[0].id != self._contact.id:
                raise forms.ValidationError(
                    ugettext("That email address is already in use."))
        return email

    def clean_postal_code(self):
        postcode = self.cleaned_data.get('postal_code')
        if not postcode and 'postal_code' not in self.required_billing_data:
            return postcode
        country = None

        if self._local_only:
            shop_config = Config.objects.get_current()
            country = shop_config.sales_country
        else:
            country = clean_field(self, 'country')

        if not country:
            # Either the store is misconfigured, or the country was
            # not supplied, so the country validation will fail and
            # we can defer the postcode validation until that's fixed.
            return postcode

        return self.validate_postcode_by_country(postcode, country)

    def clean_state(self):
        data = self.cleaned_data.get('state')
        if self._local_only:

trunk/marvin/core/contacts/templates/contact/_addressblock.html
{# output an address as a textblock #}
{% load i18n %}
<ul class="addressblock">
{% if address %}

    {% if address.description %}
    <li><strong>{{ address.description }}</strong></li>
    {% endif %}

    {% if address.is_default_billing %}
    <li><strong>{% trans "Default Billing Address" %}</strong></li>
    {% endif %}

    {% if address.is_default_shipping %}
    <li><strong>{% trans "Default Shipping Address" %}</strong></li>
    {% endif %}

    <li>{{ address.street1 }}</li>
    {% if address.street2 %}<li>{{ address.street2 }}</li>{% endif %}
    <li>{{ address.city }}{% if address.state %}, {{ address.state }}{% endif %}</li>
    {% if address.postal_code %}<li>{{ address.postal_code }}</li>{% endif %}
    <li>{{ address.country }}</li>
{% else %}
    <li>{% trans 'Not set' %}</li>
{% endif %}
</ul>

trunk/marvin/core/contacts/templates/contact/_contact_info_form_billing (Almond Development's conflicted copy 2011-07-19).html
{% load i18n %}

{% block billing-info %}
<div class="box round shadow mt20" id="billing">
    <h2>{% trans "Billing Information" %}</h2>
    <div class="inner">
<table>
    <tr><td><label for="id_addressee">{% trans "Bill To" %}</label><p class="help">{% trans "If different from the first and last names above" %}</p></td><td> {{ form.addressee }}</td></tr>
    {% if form.addressee.errors %}<tr><td class="error" colspan="2">*** {{ form.addressee.errors|join:", "}}</td></tr>{% endif %}

    <tr><td><label for="id_street1">{% trans "Street" %}{% if form.street1.field.required %}*{% endif %}</label></td><td> {{ form.street1 }}</td></tr>
    {% if form.street1.errors %}<tr><td class="error" colspan="2">*** {{ form.street1.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_street2">{% trans "Street" %}</label></td><td> {{ form.street2 }}</td></tr>
    {% if form.street2.errors %}<tr><td class="error" colspan="2">*** {{ form.street2.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_city">{% trans "City" %}{% if form.city.field.required %}*{% endif %}</label></td><td> {{ form.city }}</td></tr>
    {% if form.city.errors %}<tr><td class="error" colspan="2">*** {{ form.city.errors|join:", " }}</td></tr>{% endif %}

    {% if country %}
      {% if form.fields.state.choices %}
      <tr>
        <td><label for="id_state">{% if country.get_admin_area_display %}{{ country.get_admin_area_display }}{% else %}{% trans "State/Province" %}{% endif %} {% if form.state.field.required %}*{% endif %}</label></td>
        <td><p id="id_state_loading" style="display: none">Loading...</p> {{ form.state }}</td>
      </tr>
      {% endif %}
    {% else %}
      <tr>
        <td><label for="id_state">{% trans "State/Province" %} {% if form.state.field.required %}*{% endif %}</label></td>
        <td><p id="id_state_loading" style="display: none">Loading...</p> {{ form.state }}</td>
      </tr>
    {% endif %}
    {% if form.state.errors %}<tr><td class="error" colspan="2">*** {{ form.state.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_postal_code">{% trans "Zipcode/Postcode" %}{% if form.postal_code.field.required %}*{% endif %}</label></td><td> {{ form.postal_code }}</td></tr>
    {% if form.postal_code.errors %}<tr><td class="error" colspan="2">*** {{ form.postal_code.errors|join:", " }}</td></tr>{% endif %}

    {% if not country %}
    <tr><td><label for="id_country">{% trans "Country" %}</label></td><td> {{ form.country }}</td></tr>
    {% if form.country.errors %}<tr><td class="error" colspan="2">*** {{ form.country.errors|join:", " }}</td></tr>{% endif %}
    {% endif %}
</table>
    </div>
</div>    
{% endblock %}

trunk/marvin/core/contacts/templates/contact/_contact_info_form_billing.html
{% load i18n %}

{% block billing-info %}


<div class="box round shadow mt20">
    <a id="change_billing" class="right small magenta awesome change_address">{% trans "Change address" %}</a>
    <h2>{% trans "Billing Information" %}</h2>
    <div class="inner">
        {% if user.addresses.all %}
            <div id="all_billing_addresses">
                {% for addy in user.addresses.all %}
                    <div class="select_address">
                        <p class="addressee">{{addy.addressee}}</p>
                        <p class="street1">{{addy.street1}}</p>
                        {% if addy.street2 %}
                            <p class="street2">{{addy.street2}}</p>
                        {% endif %}
                        <p class="csp"><span class="city">{{addy.city}}</span>, <span class="state">{{addy.state}}</span> <span class="postal_code">{{addy.postal_code}}</span>
                        <p class="country">{{addy.country}}</p>
                        {% if not addy.street2 %}
                            <p>&nbsp;</p>
                        {% endif %}
                        <a class="small awesome select_billing_address_button">{% trans "Use this Address" %} »</a>
                    </div>
                {% endfor %}
                <hr />
            </div>
        {% endif %}
        <table>
            <tr><td width=50%><label for="id_addressee">{% trans "Bill To" %}</label><p class="help">{% trans "If different from the first and last names above" %}</p></td><td> {{ form.addressee }} {{ form.addressee.errors }}</td></tr>

            <tr><td><label for="id_street1">{% trans "Street" %}{% if form.street1.field.required %}*{% endif %}</label></td><td> {{ form.street1 }} {{ form.street1.errors }}</td></tr>

            <tr><td><label for="id_street2">{% trans "Street" %}</label></td><td> {{ form.street2 }} {{ form.street2.errors }}</td></tr>

            <tr><td><label for="id_city">{% trans "City" %}{% if form.city.field.required %}*{% endif %}</label></td><td> {{ form.city }} {{ form.city.errors }}</td></tr>

            {% if not country %}
            <tr><td><label for="id_country">{% trans "Country" %}</label></td><td> {{ form.country }} {{ form.country.errors }}</td></tr>
            {% endif %}

            {% if country %}
              {% if form.fields.state.choices %}
              <tr>
                <td><label for="id_state">{% if country.get_admin_area_display %}{{ country.get_admin_area_display }}{% else %}
                    {% trans "State/Province" %}{% endif %} {% if form.state.field.required %}*{% endif %}</label></td>
                <td><p id="id_state_loading" style="display: none">Loading...</p> {{ form.state }} {{ form.state.errors }}</td>
              </tr>
              {% endif %}
            {% else %}
              <tr>
                <td><label for="id_state">{% trans "State/Province" %} {% if form.state.field.required %}*{% endif %}</label></td>
                <td><p id="id_state_loading" style="display: none">Loading...</p> {{ form.state }} {{ form.state.errors }}</td>
              </tr>
            {% endif %}

            <tr><td><label for="id_postal_code">{% trans "Zipcode/Postcode" %}{% if form.postal_code.field.required %}*{% endif %}</label></td><td> {{ form.postal_code }} {{ form.postal_code.errors }}</td></tr>

        </table>
    </div>
</div>    
{% endblock %}

trunk/marvin/core/contacts/templates/contact/_contact_info_form_js.html
<script type="text/javascript">
var satchmo = satchmo || {};{% comment %}
#
# Code that require shipping fields to be present.
#
# Presently, we assume that shipping fields are always present, unless the cart
# is not shippable. This seems to hold true across both checkout and user
# account use-cases.
#
{% endcomment %}{% if cart and cart.is_shippable %}

satchmo.ship_form_toggler = function(state) {
    var inputs = $('tr.shiprow input');
    inputs.attr('disabled', state);
    var selects = $('tr.shiprow select')
    selects.attr('disabled', state);
    var rows = $('tr.shiprow');
    if (state) {
        rows.addClass('disabled');
        inputs.each(function() {
            $(this)[0].value = "";
        });
        selects.each(function() {
            $(this)[0].value = "";
        });
    } else {
        rows.removeClass('disabled');
    }
};

satchmo.update_ship_copy = function(elt) {
    var state = $(elt)[0].checked;
    satchmo.ship_form_toggler(state);
}

$(document).ready(function() {
    satchmo.update_ship_copy('#id_copy_address');
    $('#id_copy_address').click(function() {
        satchmo.update_ship_copy(this);
    });
    $('#id_addressee').bind("change", function() {
         $('#id_ship_addressee').attr('value', $('#id_addressee').attr('value'));
    });
});{% endif %}{% comment %}
#
# Code that don't require shipping fields.
#
{% endcomment %}

satchmo.name_change = function() {
    var first_name = $('#id_first_name').attr('value');
    var last_name = $('#id_last_name').attr('value');
    if (!first_name) { first_name = ''; }
    if (!last_name) { last_name = ''; }
    $('#id_addressee').attr('value',  jQuery.trim(first_name + ' ' + last_name));{% if cart and cart.is_shippable %}

    $('#id_ship_addressee').attr('value', $('#id_addressee').attr('value'));
{% endif %}
};

$(document).ready(function() {
    satchmo.name_change();
    $('#id_first_name').bind("change", {}, satchmo.name_change);
    $('#id_last_name').bind("change", {}, satchmo.name_change);
});
</script>

trunk/marvin/core/contacts/templates/contact/_contact_info_form_shipping (Almond Development's conflicted copy 2011-07-19).html
{% load i18n %}

{% block shipping-info %}
<div class="box round shadow mt20" id="shipping">
    <h2>{% trans "Shipping Information" %}</h2>
    <div class="inner">
        <table>        
    <tr><td><label for="id_copy_address">{% trans "Shipping same as billing?" %}</label></td><td> {{ form.copy_address }}</td></tr>
    {% if form.copy_address.errors %}<tr><td class="error" colspan="2">*** {{ form.copy_address.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_ship_addressee">{% trans "Ship To" %}</label><p class="help">{% trans "If different from the first and last names above" %}</td><td> {{ form.ship_addressee }}</td></tr>
    {% if form.ship_addressee.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_addressee.errors|join:", "}}</td></tr>{% endif %}

    <tr class="shiprow"><td><label for="id_ship_street1">{% trans "Street" %} {% if form.ship_street1.field.required %}*{% endif %}</label></td><td> {{ form.ship_street1 }}</td></tr>
    {% if form.ship_street1.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_street1.errors|join:", " }}</td></tr>{% endif %}

    <tr class="shiprow"><td><label for="id_ship_street2">{% trans "Street" %} {% if form.ship_street2.field.required %}*{%endif%}</label></td><td> {{ form.ship_street2 }}</td></tr>
    {% if form.ship_street2.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_street2.errors|join:", " }}</td></tr>{% endif %}

    <tr class="shiprow"><td><label for="id_ship_city">{% trans "City" %} {% if form.ship_city.field.required %}*{% endif %}</label></td><td> {{ form.ship_city }}</td></tr>
    {% if form.ship_city.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_city.errors|join:", " }}</td></tr>{% endif %}

    {% if country %}
      {% if form.fields.ship_state.choices %}
       <tr>
         <td><label for="id_ship_state">{% if country.get_admin_area_display %}{{ country.get_admin_area_display }}{% else %}{% trans "State/Province" %}{% endif %} {% if form.ship_state.field.required %}*{% endif %}</label></td>
         <td><p id="id_ship_state_loading" style="display: none">Loading...</p> {{ form.ship_state }}</td>
       </tr>
      {% endif %}
    {% else %}
      <tr class="shiprow">
        <td><label for="id_ship_state">{% trans "State/Province" %} {% if form.ship_state.field.required %}*{% endif %}</label></td>
        <td><p id="id_ship_state_loading" style="display: none">Loading...</p> {{ form.ship_state }}</td>
      </tr>
    {% endif %}
    {% if form.ship_state.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_state.errors|join:", " }}</td></tr>{% endif %}

    <tr class="shiprow"><td><label for="id_ship_postal_code">{% trans "Zipcode/Postcode" %} {% if form.ship_postal_code.field.required %}*{% endif %}</label></td><td>{{ form.ship_postal_code }}</td></tr>
    {% if form.ship_postal_code.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_postal_code.errors|join:", " }}</td></tr>{% endif %}

    {% if not country %}
    <tr class="shiprow"><td><label for="id_ship_country">{% trans "Country" %} {% if form.ship_country.field.required %}*{% endif %}</label></td><td> {{ form.ship_country }}</td></tr>
    {% if form.ship_country.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_country.errors|join:", " }}</td></tr>{% endif %}
    {% endif %}
        </table>
    </div>
</div>
{% endblock %}

trunk/marvin/core/contacts/templates/contact/_country_match_script.html
<script type="text/javascript">
var satchmo = satchmo || {};

satchmo.updating = false;

satchmo.force_match = function(elt, ship) {
    var val = $(elt).fieldValue()[0];
    if (!satchmo.updating) {
        satchmo.updating = true;
        if (ship) {
            $('#id_country').attr('value', val);
        } else {
            $('#id_ship_country').attr('value', val);
        }
        satchmo.updating = false;
    }
};

$(function() {
    satchmo.force_match($('#id_country'), false);
    $('#id_country').change(function() { satchmo.force_match(this, false) });
    $('#id_ship_country').change(function() { satchmo.force_match(this, true) });
});
</script>